version: '3.4'

services:
  kiss.bff:
    env_file:
      - .env
      - .env.local
    image: ${DOCKER_REGISTRY-}kissbff
    build:
      context: .
      dockerfile: Kiss.Bff/Dockerfile
  postgres-db:
    env_file:
      - .env
      - .env.local
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  db:
