version: "3.4"

services:
  web:
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}:latest
    build:
      context: .
      dockerfile: Kiss.Bff/Dockerfile
      target: final
  test:
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}:test
    build:
      context: .
      dockerfile: Kiss.Bff/Dockerfile
      target: test
      x-bake:
        output: testresults
