version: "3.4"

services:
  web:
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}:latest
    build:
      context: .
      dockerfile: Kiss.Bff/Dockerfile
      target: final
  npmtest:
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}:npmtest
    build:
      context: .
      dockerfile: Kiss.Bff/Dockerfile
      target: npmtest
    volumes:
      - ./testresults:/testresults
  dotnettest:
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}:dotnettest
    build:
      context: .
      dockerfile: Kiss.Bff/Dockerfile
      target: dotnettest
    volumes:
      - ./testresults:/testresults
