version: "3.4"

services:
  npmtest:
    image: ${CONTAINER_PROJECT_NAME }}:${RELEASE}_npmtest
    build:
      context: .
      dockerfile: Kiss.Bff/Dockerfile
      target: npmtest
    volumes:
      - ./testresults:/results
  dotnettest:
    image: ${CONTAINER_PROJECT_NAME }:${RELEASE}_dotnettest
    build:
      context: .
      dockerfile: Kiss.Bff/Dockerfile
      target: dotnettest
    volumes:
      - ./testresults:/results
