image:
    pullPolicy: Always
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: $(devHost)
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: kiss-frontend
          servicePort: 80
  tls:
    - hosts:
        - $(devHost)
      secretName: $(wildcardTlsSecret)
elasticstack:
    elasticHost: $(elasticHost)
    kibanaHost: $(kibanaHost)
    elasticsearch:
        ingress:
            hosts:
              - host: $(elasticHost)
                paths:
                - path: /
            tls:
              - hosts:
                  - $(elasticHost)
                secretName: $(wildcardTlsSecret)
    kibana:
        elasticsearchHost: https://elasticsearch-master:9200
        ingress:
            hosts:
              - host: $(kibanaHost)
                paths:
                  - path: /
            tls:
              - hosts:
                  - $(kibanaHost)
                secretName: $(wildcardTlsSecret)
    credentials:
        username: $(elasticUsername)
        password: $(elasticPassword)
