image:
  pullPolicy: Always
config:
  organizationIds: ["999990639"]
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k #ivm azure open id connect > nginx default buffer 8k te laag
  hosts:
    - host: www.my-website.nl
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: kiss-frontend
          servicePort: 8080
  tls:
    - hosts:
        - www.my-website.nl
      secretName: wildcard-kiss-tls
cronjobs: []
