apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kiss-frontend.fullname" . }}
  labels:
    {{- include "kiss-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kiss-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kiss-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kiss-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: environment
        configMap:
          name: {{ include "kiss-frontend.fullname" . }}
          defaultMode: 420
      - name: kvk-certs-volume
        secret:
          secretName: kvk-certs
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /usr/share/nginx/html/env.js
            subPath: env.js
            name: environment
            readOnly: true
          - name: kvk-certs-volume
            mountPath: /usr/local/share/ca-certificates
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:  # Add your environment variables here
          - name: OIDC_CLIENT_SECRET
            value: {{ .Values.env.OIDC_CLIENT_SECRET | quote }}
          - name: OIDC_CLIENT_ID
            value: {{ .Values.env.OIDC_CLIENT_ID | quote }}
          - name: OIDC_AUTHORITY
            value: {{ .Values.env.OIDC_AUTHORITY | quote }}
          - name: KVK_BASE_URL
            value: {{ .Values.env.KVK_BASE_URL | quote }}
          - name: KVK_API_KEY
            value: {{ .Values.env.KVK_API_KEY | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
