apiVersion: v1
entries:
  kiss-frontend:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-01-04T10:21:14.128292723+01:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 1.2.0
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.2.1
    - alias: gatewayui
      name: skeleton-app
      repository: https://raw.githubusercontent.com/ConductionNL/gateway-ui/demo/helm/
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 6de26e8abd37af3779c50405631fc2197f37cde9d107852421b6747fb6eea337
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-01-04T10:21:14.038743379+01:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 1.2.0
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.1.0
    - alias: gatewayui
      name: skeleton-app
      repository: https://raw.githubusercontent.com/ConductionNL/gateway-ui/demo/helm/
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 851fa5a0c4a664d5bb5beef9728ff504e3da126a135d6469dd452d085e8a28f2
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 0.1.8
    created: "2023-01-04T10:21:13.967402229+01:00"
    description: A Helm chart for Kubernetes
    digest: 9a1722bdcc63d3a201f8d736251f31b120073800093efd8fcc05e25ff5926311
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2023-01-04T10:21:13.96280927+01:00"
    description: A Helm chart for Kubernetes
    digest: 95f320705b4b5cdf03e4938f6499c2fc3e86d33e3cdfcf03b9553956500a578d
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 0.1.6
    created: "2023-01-04T10:21:13.957475717+01:00"
    description: A Helm chart for Kubernetes
    digest: 9912bb338ba6afd0d56915ffd6c8fc80d0190c1a334e56767993a75be4f2a3c7
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.1.5
    created: "2023-01-04T10:21:13.951418444+01:00"
    description: A Helm chart for Kubernetes
    digest: 6cd87ea25b4f3c8c915e06af88cc3169ea0d3f8e6f4a92b11da699fa8290d138
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2023-01-04T10:21:13.94665533+01:00"
    description: A Helm chart for Kubernetes
    digest: bad87a629e1ff53a1544013101020de24d8cde28d0df2a7aaca2c6accb84c8c4
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2023-01-04T10:21:13.942424705+01:00"
    description: A Helm chart for Kubernetes
    digest: cd56ddc531f2690cebd170a17a5cc4553858cb79ec026ec21f5cadde4a260827
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2023-01-04T10:21:13.937411718+01:00"
    description: A Helm chart for Kubernetes
    digest: 7533cf47752696221a6e34d6afe93b0226b789722336341568ba1c867bb917a1
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2023-01-04T10:21:13.933145553+01:00"
    description: A Helm chart for Kubernetes
    digest: 5caac7f24fc53757078d8353a431f23e59fe3e9c051509cf89ade9e132b89489
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-01-04T10:21:13.928099488+01:00"
    description: A Helm chart for Kubernetes
    digest: 23b0e1db8ffb0d2018f7cf87007b22a9fb3164ff09b2644e04bb57190b2be5ad
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.0.tgz
    version: 0.1.0
generated: "2023-01-04T10:21:13.923904045+01:00"
