apiVersion: v1
entries:
  kiss-frontend:
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2022-06-15T16:33:11.108853712+02:00"
    description: A Helm chart for Kubernetes
    digest: bad87a629e1ff53a1544013101020de24d8cde28d0df2a7aaca2c6accb84c8c4
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2022-06-15T16:33:11.105137321+02:00"
    description: A Helm chart for Kubernetes
    digest: cd56ddc531f2690cebd170a17a5cc4553858cb79ec026ec21f5cadde4a260827
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2022-06-15T16:33:11.100960027+02:00"
    description: A Helm chart for Kubernetes
    digest: 7533cf47752696221a6e34d6afe93b0226b789722336341568ba1c867bb917a1
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2022-06-15T16:33:11.097489742+02:00"
    description: A Helm chart for Kubernetes
    digest: 5caac7f24fc53757078d8353a431f23e59fe3e9c051509cf89ade9e132b89489
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-06-15T16:33:11.094426738+02:00"
    description: A Helm chart for Kubernetes
    digest: 23b0e1db8ffb0d2018f7cf87007b22a9fb3164ff09b2644e04bb57190b2be5ad
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.0.tgz
    version: 0.1.0
generated: "2022-06-15T16:33:11.08920705+02:00"
