apiVersion: v1
entries:
  kiss-frontend:
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2022-05-20T15:15:53.028905058+02:00"
    description: A Helm chart for Kubernetes
    digest: 0277dd05e0bbdec354071a71bfad1ab9192cfb48dcb4604e63160e320e2d56b4
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-05-20T15:15:53.025932334+02:00"
    description: A Helm chart for Kubernetes
    digest: 23b0e1db8ffb0d2018f7cf87007b22a9fb3164ff09b2644e04bb57190b2be5ad
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-0.1.0.tgz
    version: 0.1.0
generated: "2022-05-20T15:15:53.02197955+02:00"
