name: Docker CI

on:
  pull_request:
    branches:
    - main
    - acceptance
    - development

  push:
    branches:
    - main
    - acceptance
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.2
      - name: npm setup
        uses: ng-easy/npm-setup@v1.7.2
      - name: Build npm
        run: npm run build
      