name: Playwright Tests
on:
  schedule:
    - cron: '0 23 * * *'
  pull_request:
    branches: [ main, master ]
    paths: ['Kiss.Bff.EndToEndTest/**']
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Kiss.Bff.EndToEndTest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet build
    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run your tests
      id: e2e
      run: dotnet test
      env:
        'TestSettings:TEST_USERNAME': ${{ secrets.PLAYWRIGHT_USERNAME }}
        'TestSettings:TEST_PASSWORD': '${{ secrets.PLAYWRIGHT_PASSWORD }}'
        'TestSettings:TEST_TOTP_SECRET': ${{ secrets.PLAYWRIGHT_TOTP_SECRET }}
        'TestSettings:TEST_BASE_URL': ${{ secrets.PLAYWRIGHT_BASE_URL }}
    - name: Deploy to GitHub Pages
      if: ${{ always() }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Kiss.Bff.EndToEndTest/bin/Debug/net8.0/playwright-traces # directory of your reports
        publish_branch: gh-pages/e2e # deploying to gh-pages branch

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false